//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA_Migalkina_PM_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID_request { get; set; }
        public string type { get; set; }
        public string serial_number { get; set; }
        public string problem_description { get; set; }
        public int ID_user { get; set; }
        public Nullable<int> ID_worker { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
