//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AA_Migalkina_PM_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int ID_role { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<int> ID_Managers { get; set; }
        public Nullable<int> ID_worker { get; set; }
    
        public virtual Managers Managers { get; set; }
        public virtual Users Users { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
